name: "Test"
on:
  pull_request:

jobs:
  lints:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-24.11
      - uses: cachix/cachix-action@v15
        with:
          name: foundationdb
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - run: nix flake check --all-systems

  build-cache:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        package: [foundationdb71, foundationdb73, fdbexplorer]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-24.11
      - uses: cachix/cachix-action@v15
        with:
          name: nixpkgs-cross-overlay
      - uses: cachix/cachix-action@v15
        with:
          name: foundationdb
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v6

      - name: "Runner information"
        run: uname -a

      - name: "Build Packages"
        run: nix build ".#${{ matrix.package }}"
